#!/bin/bash

# Start the application httpd instance

# Exit on any errors
set -e

# Get gear ip address.
gip=$(facter ipaddress)

#
# Publish this gear's HTTP URL/endpoint.
#
echo "${OPENSHIFT_GEAR_DNS}|${gip}:${OPENSHIFT_JBOSS_UNIFIED_PUSH_HTTP_PROXY_PORT}"
